name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy-docs.yml'

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy MkDocs to GitHub Pages
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install mkdocs-material pymdown-extensions

    - name: Deploy documentation
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        mkdocs gh-deploy --force
